---
RZ\Roadiz\CoreBundle\Entity\Folder:
    operations:
        ApiPlatform\Metadata\GetCollection:
            method: "GET"
            normalizationContext:
                groups: [ "folder" ]
                enable_max_depth: true
        ApiPlatform\Metadata\Get:
            method: "GET"
            normalizationContext:
                groups: [ "folder" ]
                enable_max_depth: true
