---
RZ\Roadiz\CoreBundle\Entity\Realm:
    operations:
        ApiPlatform\Metadata\GetCollection:
            method: "GET"
            normalizationContext:
                groups: [ "realm" ]
                enable_max_depth: true

        ApiPlatform\Metadata\Get:
            method: "GET"
            normalizationContext:
                groups: [ "realm" ]
                enable_max_depth: true
