---
RZ\Roadiz\CoreBundle\Entity\Translation:
    operations:
        ApiPlatform\Metadata\GetCollection:
            method: "GET"
            normalizationContext:
                enable_max_depth: true
                groups:
                    - translation_base

        ApiPlatform\Metadata\Get:
            method: 'GET'
            normalizationContext:
                enable_max_depth: true
                groups:
                    - translation_base

